### ISSUE TITLE
Bundle refuses to get 0.6.11 in Rails 5

### ISSUE THREAD

**Issue by ianjhoffman** [YourCursus/perfect-scrollbar-rails#3]
Is there a version of the perfect-scrollbar-rails that works with Rails 5.0.0? I'm making a Rails 5 app and bundle is not happy about the dependencies of the current version of perfect-scrollbar-rails.

**Comment by zedtux** [comment]
I'm also building a Rails 5 app using this gem and it works fine. Can you please provide more information?
